- name: Shutdown SFF Hosts
  hosts: sff_hosts_as_root
  become: true
  tasks:
    - name: Shutdown servers (10 second delay)
      ansible.builtin.shutdown:
        delay: 10
        msg: "ALERT: The system is shutting down in 10 seconds."
      ignore_unreachable: true
